/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.skydragonsz.testing;



public class App {
    private String botToken = "NzE5OTE4MTg1MTIxMzE2OTA0.Xt-oAQ.uZnThZlWiyRteCWEwL1GpdeSI-E";
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
